-- Create foreign key PRODUTOS_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM PRODUTOS;

DROP TABLE PRODUTOS;

CREATE TABLE PRODUTOS (
	PRODUTO_CODIGO INTEGER,
	PRODUTO_NOME TEXT NOT NULL,
	PRATELEIRA_ID INTEGER,
	PRODUTO_QUANTIDADE INTEGER,
	PRODUTO_VALOR FLOAT DEFAULT '0' NOT NULL,
	CONSTRAINT PRODUTOS_FK FOREIGN KEY (PRATELEIRA_ID) REFERENCES PRATELEIRAS(PRATELEIRA_CODIGO) ON DELETE RESTRICT
);

INSERT INTO PRODUTOS
SELECT *
FROM temp;

DROP TABLE temp;

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM CLIENTES;

DROP TABLE CLIENTES;

CREATE TABLE CLIENTES (
	CLIENTE_CODIGO INTEGER PRIMARY KEY AUTOINCREMENT,
	CLIENTE_NOME TEXT NOT NULL,
	CLIENTE_TELEFONE INTEGER NOT NULL,
	CLIENTE_CPF INTEGER NOT NULL,
	CLIENTE_TOTAL_COMPRAS INTEGER NOT NULL,
	CLIENTE_CIDADE_ID INTEGER NOT NULL,
	CONSTRAINT CLIENTES_FK FOREIGN KEY (CLIENTE_CIDADE_ID) REFERENCES CIDADES(CIDADE_ID) ON DELETE RESTRICT
);

INSERT INTO CLIENTES
SELECT *
FROM temp;

DROP TABLE temp;

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM ITENS_CUPOM_FISCAL;

DROP TABLE ITENS_CUPOM_FISCAL;

CREATE TABLE ITENS_CUPOM_FISCAL (
	 ITEN_CUPOM_FISCAL_CODIGO INTEGER  PRIMARY KEY AUTOINCREMENT ,
    ITEN_CUPOM_FISCAL_NUMERO INTEGER,
    ITEN_CUPOM_FISCAL_SEQUENCIA INTEGER NOT NULL ,
    ITEN_CUPOM_FISCAL_PRODUTO INTEGER  NOT NULL ,
    ITEN_CUPOM_FISCAL_QUANTIDADE FLOAT  NOT NULL ,
    ITEN_CUPOM_FISCAL_VALOR_UN FLOAT  NOT NULL DEFAULT '0',
    ITEN_CUPOM_FISCAL_VALOR_TOT FLOAT  NOT NULL DEFAULT '0',
	CONSTRAINT ITENS_CUPOM_FISCAL_FK FOREIGN KEY (ITEN_CUPOM_FISCAL_PRODUTO) REFERENCES PRODUTOS(PRODUTO_CODIGO) ON DELETE RESTRICT
);

INSERT INTO ITENS_CUPOM_FISCAL
SELECT *
FROM temp;

DROP TABLE temp;

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM NOTAS;

DROP TABLE NOTAS;

CREATE TABLE NOTAS (
	NOTA_ID INTEGER NOT NULL,
	NOTA_DATA_DE_EMISSAO TEXT NOT NULL,
	NOTA_CLIENTE TEXT NOT NULL,
	NOTA_ATENDENTE TEXT NOT NULL,
	CONSTRAINT NOTAS_FK FOREIGN KEY (NOTA_CLIENTE) REFERENCES CLIENTES(CLIENTE_CODIGO) ON DELETE RESTRICT,
	CONSTRAINT NOTAS_FK_1 FOREIGN KEY (NOTA_ATENDENTE) REFERENCES ATENDENTES(ATENDENTE_CODIGO) ON DELETE RESTRICT,
	CONSTRAINT NOTAS_FK_2 FOREIGN KEY (NOTA_ID) REFERENCES ITENS_CUPOM_FISCAL(ITEN_CUPOM_FISCAL_CODIGO) ON DELETE RESTRICT
);

INSERT INTO NOTAS
SELECT *
FROM temp;

DROP TABLE temp;