BEGIN TRANSACTION;

DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE PESSOAS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT ,
    CPF         TEXT    NOT NULL,
    NOME        TEXT    NOT NULL,
    IDADE       INT     NOT NULL,
    ENDERECO    CHAR(50),
    CIDADE      TEXT,
    SALARIO     REAL
);

BEGIN TRANSACTION;

INSERT INTO PESSOAS (CPF,NOME,IDADE,ENDERECO,SALARIO)
    VALUES
    ('123.456.789-00','Débora',19,'Rua Dorvino Coradini, 101',10000.00)
    ('123.456.789-11','Alice',4,'Rua Dorvino Coradini, 101',1000.00)


COMMIT;